# -*- coding: utf-8 -*-
"""Multi-item Dynamic Economic Order Quantity For Non B2B Card Board Product.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D-h29eedhW16vAgHBO3zE5myG02-T5gj

Multi-item EOQ
"""

import math
import pandas as pd

def calculate_multi_item_eoq(items_info):
    """
    Calculate the Economic Order Quantity (EOQ) for Multi-Item Orders.

    Args:
        items_info (list): List of tuples containing item information (demand, ordering cost, carrying cost).

    Returns:
        list: Calculated EOQ for each item.
    """
    eoq_list = []
    for item in items_info:
        demand, ordering_cost, carrying_cost = item
        eoq = math.sqrt((2 * demand * ordering_cost) / carrying_cost)
        if eoq > demand:
            eoq = demand
        else:
            eoq = eoq
        eoq_list.append(eoq)
    return eoq_list

"""Now, for all months in the data"""

# Import data dari file excel
Jan = pd.read_excel('Data Karton Non B2B.xlsx',sheet_name='Jan')
Feb = pd.read_excel('Data Karton Non B2B.xlsx',sheet_name='Feb')
Mar = pd.read_excel('Data Karton Non B2B.xlsx',sheet_name='Mar')
Apr = pd.read_excel('Data Karton Non B2B.xlsx',sheet_name='Apr')
May = pd.read_excel('Data Karton Non B2B.xlsx',sheet_name='Mei')
Jun = pd.read_excel('Data Karton Non B2B.xlsx',sheet_name='Juni')
Jul = pd.read_excel('Data Karton Non B2B.xlsx',sheet_name='Juli')
Aug = pd.read_excel('Data Karton Non B2B.xlsx',sheet_name='Aug')

# Ambil nama tiap item
Jan_items = Jan['Item']
Jan_items = Jan_items.tolist()
Feb_items = Feb['Item']
Feb_items = Feb_items.tolist()
Mar_items = Mar['Item']
Mar_items = Mar_items.tolist()
Apr_items = Apr['Item']
Apr_items = Apr_items.tolist()
May_items = May['Item']
May_items = May_items.tolist()
Jun_items = Jun['Item']
Jun_items = Jun_items.tolist()
Jul_items = Jul['Item']
Jul_items = Jul_items.tolist()
Aug_items = Aug['Item']
Aug_items = Aug_items.tolist()

# Hapus kolom pertama
Jan_data = Jan.iloc[:, 1:4]
Feb_data = Feb.iloc[:, 1:4]
Mar_data = Mar.iloc[:, 1:4]
Apr_data = Apr.iloc[:, 1:4]
May_data = May.iloc[:, 1:4]
Jun_data = Jun.iloc[:, 1:4]
Jul_data = Jul.iloc[:, 1:4]
Aug_data = Aug.iloc[:, 1:4]

# Ubah data frame menjadi list
Jan_list = Jan_data.values.tolist()
Feb_list = Feb_data.values.tolist()
Mar_list = Mar_data.values.tolist()
Apr_list = Apr_data.values.tolist()
May_list = May_data.values.tolist()
Jun_list = Jun_data.values.tolist()
Jul_list = Jul_data.values.tolist()
Aug_list = Aug_data.values.tolist()

# Extract Ordering Cost
Jan_oc = Jan_data['Ordering Cost'].values.tolist()
Feb_oc = Feb_data['Ordering Cost'].values.tolist()
Mar_oc = Mar_data['Ordering Cost'].values.tolist()
Apr_oc = Apr_data['Ordering Cost'].values.tolist()
May_oc = May_data['Ordering Cost'].values.tolist()
Jun_oc = Jun_data['Ordering Cost'].values.tolist()
Jul_oc = Jul_data['Ordering Cost'].values.tolist()
Aug_oc = Aug_data['Ordering Cost'].values.tolist()

Jan_k = Jan['Keluar'].values.tolist()
Feb_k = Feb['Keluar'].values.tolist()
Mar_k = Mar['Keluar'].values.tolist()
Apr_k = Apr['Keluar'].values.tolist()
May_k = May['Keluar'].values.tolist()
Jun_k = Jun['Keluar'].values.tolist()
Jul_k = Jul['Keluar'].values.tolist()
Aug_k = Aug['Keluar'].values.tolist()

Jan_hk = Jan['Hari Kerja'].values.tolist()
Feb_hk = Feb['Hari Kerja'].values.tolist()
Mar_hk = Mar['Hari Kerja'].values.tolist()
Apr_hk = Apr['Hari Kerja'].values.tolist()
May_hk = May['Hari Kerja'].values.tolist()
Jun_hk = Jun['Hari Kerja'].values.tolist()
Jul_hk = Jul['Hari Kerja'].values.tolist()
Aug_hk = Aug['Hari Kerja'].values.tolist()

Jan_eoqs = calculate_multi_item_eoq(Jan_list)
Feb_eoqs = calculate_multi_item_eoq(Feb_list)
Mar_eoqs = calculate_multi_item_eoq(Mar_list)
Apr_eoqs = calculate_multi_item_eoq(Apr_list)
May_eoqs = calculate_multi_item_eoq(May_list)
Jun_eoqs = calculate_multi_item_eoq(Jun_list)
Jul_eoqs = calculate_multi_item_eoq(Jul_list)
Aug_eoqs = calculate_multi_item_eoq(Aug_list)

# Mengubah calculates_eoqs menjadi list
Jan_eoqs = list(map(int, Jan_eoqs))
Feb_eoqs = list(map(int, Feb_eoqs))
Mar_eoqs = list(map(int, Mar_eoqs))
Apr_eoqs = list(map(int, Apr_eoqs))
May_eoqs = list(map(int, May_eoqs))
Jun_eoqs = list(map(int, Jun_eoqs))
Jul_eoqs = list(map(int, Jul_eoqs))
Aug_eoqs = list(map(int, Aug_eoqs))

# Menggabungkan dan menghilangkan duplikat
unique_items = list(set(Jan_items + Feb_items + Mar_items + Apr_items + May_items + Jun_items + Jul_items + Aug_items))

# Membuat DataFrame dengan index unik
df1 = pd.DataFrame(index=unique_items)
df2 = pd.DataFrame(index=unique_items)
df3 = pd.DataFrame(index=unique_items)
df4 = pd.DataFrame(index=unique_items)
df5 = pd.DataFrame(index=unique_items)

# Data bulan-bulan dan item-items
months = ['Jan','Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug']
month_items = [Jan_items, Feb_items, Mar_items, Apr_items, May_items, Jun_items, Jul_items, Aug_items]
month_eoqs = [Jan_eoqs, Feb_eoqs, Mar_eoqs, Apr_eoqs, May_eoqs, Jun_eoqs, Jul_eoqs, Aug_eoqs]
month_oc = [Jan_oc, Feb_oc, Mar_oc, Apr_oc, May_oc, Jun_oc, Jul_oc, Aug_oc]
month_k = [Jan_k, Feb_k, Mar_k, Apr_k, May_k, Jun_k, Jul_k, Aug_k]
month_hk = [Jan_hk, Feb_hk, Mar_hk, Apr_hk, May_hk, Jun_hk, Jul_hk, Aug_hk]
month_values = [Jan_data['Saldo'].values.tolist(), Feb_data['Saldo'].values.tolist(), Mar_data['Saldo'].values.tolist(), Apr_data['Saldo'].values.tolist(), May_data['Saldo'].values.tolist(), Jun_data['Saldo'].values.tolist(), Jul_data['Saldo'].values.tolist(), Aug_data['Saldo'].values.tolist()]

# Looping untuk_mengisi nilai untuk_setiap kolom berdasarkan bulan-bulan
for month, items, eoqs in zip(months, month_items, month_eoqs):
    df1[month] = [eoqs[items.index(item)] if item in items else None for item in unique_items]

for month, items, oc in zip(months, month_items, month_oc):
    df2[month] = [oc[items.index(item)] if item in items else None for item in unique_items]

for month, items, k in zip(months, month_items, month_k):
    df3[month] = [k[items.index(item)] if item in items else None for item in unique_items]

for month, items, hk in zip(months, month_items, month_hk):
    df4[month] = [hk[items.index(item)] if item in items else None for item in unique_items]

for month, items, values in zip(months, month_items, month_values):
    df5[month] = [values[items.index(item)] if item in items else None for item in unique_items]

df2['Average OC'] = df2.apply(lambda row: row.mean(skipna=True), axis=1)
df3['Minimum Keluar'] = df3.min(axis=1)
df3['Average Keluar'] = df3.apply(lambda row: row.mean(skipna=True), axis=1)
df4['Average Hari Kerja'] = df4.apply(lambda row: row.mean(skipna=True), axis=1)
df5['Maximum Values'] = df5.max(axis=1)

df1['Average OC'] = df2['Average OC']
df1['Minimum Keluar'] = df3['Minimum Keluar']
df1['Average Keluar'] = df3['Average Keluar']
df1['Average Hari Kerja'] = df4['Average Hari Kerja']
df1['Maximum Values'] = df5['Maximum Values']

# Export DataFrame to Excel
df1.to_excel('Multi-item EOQ Karton Non B2B.xlsx')

"""Dynamic EOQ"""

import math

def calculate_dynamic_eoq(demand_profile,
                          cost_of_ordering,
                          cost_of_carrying):
    """
    Calculate the Economic Order Quantity (EOQ) using a Dynamic EOQ model.

    Args:
        demand_profile (list): List of demand values over time.
        cost_of_ordering (float): Cost of placing an order.
        cost_of_carrying (float): Cost of carrying one unit of inventory for a period.

    Returns:
        float: Calculated Dynamic EOQ.
    """
    total_demand = sum(demand_profile)
    average_demand = total_demand / len(demand_profile)

    variability_sum = sum([(demand - average_demand) ** 2 for demand in demand_profile])
    demand_variance = variability_sum / (len(demand_profile) - 1)
    demand_standard_deviation = math.sqrt(demand_variance)
    dynamic_squared = (2 * total_demand * cost_of_ordering) / (cost_of_carrying * (1 - (demand_standard_deviation / average_demand)))
    if dynamic_squared < 0:
      dynamic_squared = 0
    else:
      dynamic_squared = dynamic_squared
    dynamic_eoq = math.sqrt(dynamic_squared)
    if dynamic_eoq > max(demand_profile):
      dynamic_eoq = max(demand_profile)
    else:
      dynamic_eoq = dynamic_eoq
    return dynamic_eoq

ordering_cost = df1['Average OC'].values
ordering_cost = ordering_cost.tolist()

df6 = df1.copy()
df6.drop(columns=['Average OC','Minimum Keluar', 'Average Keluar', 'Average Hari Kerja','Maximum Values'], axis=1, inplace=True)
df6_list = df6.values.tolist()

def remove_nan_and_zero(lst):
  """
  Removes NaN and 0 values from a list.

  Args:
    lst: The list to be cleaned.

  Returns:
    A new list with NaN and 0 values removed.
  """
  return [x for x in lst if not (pd.isna(x) or x == 0)]

Multi_DEOQ_result = pd.DataFrame({'item names': df3.index})

# List untuk menyimpan hasil perhitungan
result_list = []

# Looping untuk menghitung calculate_dynamic_eoq() untuk setiap baris
for i in range(len(df6_list)):
    if len(remove_nan_and_zero(df6_list[i])) == 1:
        result = remove_nan_and_zero(df6_list[i])
    elif remove_nan_and_zero(df6_list[i]) == 0:
        result = 0
    elif len(remove_nan_and_zero(df6_list[i])) == 0:
        result = 0
    else:
        result = calculate_dynamic_eoq(remove_nan_and_zero(df6_list[i]), ordering_cost[i], 26.8642110159069)
    print(f"Proses ke-{i+1}:")
    print(result)
    result_list.append(result)

# Menambahkan kolom baru ke DataFrame
Multi_DEOQ_result['Multi-item Dynamic EOQ'] = result_list
Multi_DEOQ_result.to_excel('Multi-item Dynamic EOQ for Non B2B Card Board Product.xlsx')